# Generated by Django 5.1 on 2024-08-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_author_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Design')], default='1', max_length=2),
        ),
    ]
