# Generated by Django 5.1 on 2024-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_text_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
