# Generated by Django 5.1 on 2024-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_author_bio_author_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
