# Generated by Django 5.1 on 2024-08-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
